---
scale_graph : True #True or False
model : "sentence_sim"
storage : "demo/text_processed.csv"
storage_examples :  "demo/examples.csv"
sentence_segmentation_method : "punct_commas" #spacy, punctuation, punct_commas

paragraph_size : 5
nb_examples : 2 #number of examples per modes to extract, multiply by 3 for the total number/text
nb_texts : 0 #0 for all texts
